[package]
name = "clitch"
version = "0.1.0-alpha"
edition = "2021"

[dependencies]
chrono = "0.4"
chrono-tz = "0.8"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.27"
iana-time-zone = "0.1"
